"""add reset password fields

Revision ID: 181fdc7c9fe0
Revises: 1e9b6471f99a
Create Date: 2026-07-23 20:21:17.933029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181fdc7c9fe0'
down_revision = '1e9b6471f99a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_password_token_expire', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_password_token_expire')
    op.drop_column('users', 'reset_password_token')
    # ### end Alembic commands ###
